title: Conference Deadlines
description: Countdowns to conference deadlines
author: Research Group Visual Analytics

domain: "tibhannover.github.io"
baseurl: "/va-deadlines"

twitter_hashtag:
github_username: TIBHannover
github_repo: va-deadlines

markdown: kramdown
ga_id:

include: ["_pages"]
